# Generated by Django 3.2.5 on 2021-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('regionName', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
